kind = "mobile"
previewPath = "/"
title = "Wonder Hub Prediction"
version = "1.0.0"
id = "artifacts/wonder-hub"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23943

[services.development]
run = "pnpm --filter @workspace/wonder-hub run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wonder-hub", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/wonder-hub", "run", "serve" ]

[services.env]
PORT = "23943"
BASE_PATH = "/"
